In [9]:
print("Hola mundo")

Hola mundo


In [10]:
x = 1


In [2]:
print(x)

NameError: name 'x' is not defined

In [4]:
a = 1
b = 2
c= 3
print(a + b + c)

6


This is a text

*cursive text*

In [16]:
v=[10,20,40,20,20,33,42,92,14,56]


In [17]:
print(v)

[10, 20, 40, 20, 20, 33, 42, 92, 14, 56]


In [18]:
23 in v

False

In [19]:
10 in v 

True

In [22]:
print(v[5])

33


In [24]:
v[-1]

56

In [25]:
v[0]=23
print(v[0])
print(v)

23
[23, 20, 40, 20, 20, 33, 42, 92, 14, 56]


In [27]:
print(len(v))
print(v[5])

10
33


In [29]:
print("la suma de los primeros dos valores es:",v[0]+v[1])

la suma de los primeros dos valores es: 43


In [30]:
print(v)
v.append(77)
print(v)

[23, 20, 40, 20, 20, 33, 42, 92, 14, 56]
[23, 20, 40, 20, 20, 33, 42, 92, 14, 56, 77]


In [47]:
print(v)
v.append(87)
print(v)

[42, 77, 22, 2, 45, 5]
[42, 77, 22, 2, 45, 5, 87]


In [32]:
print(v)
v.remove("Hola")
print(v)

[23, 20, 40, 20, 20, 33, 42, 92, 14, 56, 77, 'Hola']
[23, 20, 40, 20, 20, 33, 42, 92, 14, 56, 77]


In [42]:
print(v)
a=v.pop(0)
print(v)
print(a)

[33, 42, 77]
[42, 77]
33


In [48]:
print(v)
v.sort()
print(v)

[42, 77, 22, 2, 45, 5, 87]
[2, 5, 22, 42, 45, 77, 87]


In [49]:
t1=(1,2,3,4,5,6,7,8)

In [50]:
t1[3]

4

In [54]:
for i in v:
    print(i)
    print("Hola ciclo")   

2
Hola ciclo
5
Hola ciclo
22
Hola ciclo
42
Hola ciclo
45
Hola ciclo
77
Hola ciclo
87
Hola ciclo


In [58]:
print(list(range(30,400,30)))


[30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360, 390]


In [63]:
for i in range(1):
    print(i)
    print("Hola")

0
Hola


In [66]:
print(v)
for i in v:
    print(i**2)

[2, 5, 22, 42, 45, 77, 87]
4
25
484
1764
2025
5929
7569


In [101]:
v2=list(range(10,20))
v3=list(range(15,25))

print(v2)
print(v3)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [102]:
print("La longitud de v2 es ")
print(len(v2))
print("La longitud de v3 es ")
print(len(v3))
if len(v2)==len(v3):
    print("Misma Longitud")
elif len(v2)==len(v3)+1:
    print("La longitud del v2 es 1 unidad mayor")
else:
    print("Diferente longitud")

La longitud de v2 es 
10
La longitud de v3 es 
10
Misma Longitud


**Combinación entre FOR e IF**

In [108]:
if len(v2)==len(v3):
    for i in range(0,len(v2)):
        if v2[i] in v3:
            print(v2[i])
else:
    print("Diferente longitud")

15
16
17
18
19


**Nomenclatura comprimida del cliclo FOR con listas**


In [112]:
[i for i in v]

[2, 5, 22, 42, 45, 77, 87]

In [113]:
[i**2 for i in v]

[4, 25, 484, 1764, 2025, 5929, 7569]

In [124]:
print(v)
[i for i in v if i> 30]

[2, 5, 22, 42, 45, 77, 87]


[42, 45, 77, 87]

**ALEATORIOS, FUNCIONES Y CICLO WHILE**

In [6]:
import random as rnd

**Aleatorio entero**

In [7]:
rnd.randint(0,20)

18

*Aqui requerimos 10 numeros aleatorios en un rango de 500 a 900*  rnd.randint(500,900)  
*Aqui el ciclo **FOR** se va ejecutar 10 veces hasta dar los 10 numeros aleatorios*

In [8]:
[rnd.randint(500,900) for i in range(0,10)]

[857, 801, 560, 561, 596, 651, 733, 623, 568, 735]

# **Funciones**

** Aqui vamos a definir una función que contendrá las instrucciones siguientes:    dar una lista de numero aleatoreos con un rango de numeros que vamos a definir, asi como el tamaño del rango **

In [16]:
def listaAleatorios(limiteInf,limiteSup,tamaño):
    return[rnd.randint(limiteInf,limiteSup) for i in range (0,tamaño)]

In [17]:
listaPrueba=listaAleatorios(50,100,20)
print(listaPrueba)

[50, 95, 97, 57, 60, 96, 67, 95, 68, 92, 96, 94, 57, 73, 85, 66, 76, 58, 82, 68]


*A continuación, voy a sacar un promedio con una función; voy a crear una función que arroje el promedio de una lista, dentro de la funcion promedio, estará la función listaAleatorios*

In [18]:
def promedio(lista):
    suma=0
    for elemento in lista:
        suma= suma+elemento
    prom=suma/len(lista)
    return prom
    

In [19]:
print(promedio(listaAleatorios(30,300,5)))

190.6


# WHILE  
### Funciona parecido al ciclo for, solo que este ciclo está diseñado a que se termine cuand ouna condición u operación booleana de como resultado FALSE.

*A continuación se va hacer un ciclo while, donde se asignarán valoreas aleatorios, y terminará el ciclo
cuando salga un numero aleatorio > 90 , por que a cambiará a 1 y ya no se va a 
cumplir la condición WHILE*

In [20]:
a=0
while a==0:
    aleatorio=rnd.randint(50,100)
    print(aleatorio)
    if aleatorio>90:
        a=1

51
97


*A continuación se va a crear una lista, con un rango de 5 números a los que se les va a
sacar el promedio, y el ciclo WHILE se detendrá cuando el promedio de la lista sea mayor < a 60*

In [27]:
lista=[0 for i in range(0,10)]
while promedio(lista)<60:
    lista=listaAleatorios(0,100,10)
    print(lista,promedio(lista))    

[95, 5, 96, 30, 11, 79, 60, 60, 55, 55] 54.6
[85, 75, 83, 10, 0, 73, 35, 94, 8, 74] 53.7
[28, 58, 46, 94, 87, 94, 26, 25, 71, 75] 60.4


# Diccionarios

*  Los diccionarios son estructuras de datos donde el identificador son pares de llaves con valores
las llaves no son iterables(no se pueden modificar), las llaves guardan espacio en la memoria*

In [18]:
dict1= {'nombre':['itzel','cesar','erandi'],
        'apellidos':['jaimes','ramirez','jaimes']}

In [19]:
dict1.keys()

dict_keys(['nombre', 'apellidos'])

In [20]:
dict1.values()

dict_values([['itzel', 'cesar', 'erandi'], ['jaimes', 'ramirez', 'jaimes']])

In [21]:
dict1['nombre']

['itzel', 'cesar', 'erandi']

In [22]:
dict1['apellidos']

['jaimes', 'ramirez', 'jaimes']

*NO puedes cambiar las keys, pero si agregar nuevas llaves*

In [25]:
print(dict1)

{'nombre': ['itzel', 'cesar', 'erandi'], 'apellidos': ['jaimes', 'ramirez', 'jaimes']}


*Aqui se observa como se modifica el valor de la key edades*

In [28]:
dict1['edades']=[27,28,19]

In [33]:
print(dict1)

{'nombre': ['itzel', 'cesar', 'erandi'], 'apellidos': ['jaimes', 'ramirez', 'jaimes'], 'edades': [26, 28, 19]}


In [36]:
dict1['edades'][0]=26
dict1['edades']

[26, 28, 19]

In [38]:
for item in dict1.items():
    print (item)

('nombre', ['itzel', 'cesar', 'erandi'])
('apellidos', ['jaimes', 'ramirez', 'jaimes'])
('edades', [26, 28, 19])


In [41]:
for key in dict1.keys():
    print(key,dict1[key])

nombre ['itzel', 'cesar', 'erandi']
apellidos ['jaimes', 'ramirez', 'jaimes']
edades [26, 28, 19]


## ** Numpy **
*Es un paquete para ciencia de datos que contiene funciones complejas para hacer calculos matematicos*

# * Arrays *

Un array o un arreglo es un vector, similar a las listas de python, solo que con la libreria de numpy puede llegar a ser muy eficiente

Importando la libreria de numpy

In [1]:
import numpy as np

Después creamos el arreglo usando la función array que recibe información dentro de  []

In [2]:
vector = np.array([0,1,2,3])

In [3]:
vector

array([0, 1, 2, 3])

In [4]:
print(vector)

[0 1 2 3]


In [15]:
L = range(1000)
%timeit [i**2 for i in L]

284 µs ± 4.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
a = np.arange(1000)
%timeit a**2

1.29 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
eficiencia = 284/1.29
print("veces mas rapido np que python {}".format(eficiencia))

veces mas rapido np que python 220.15503875968992


In [23]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Manipulación de arrays en numpy 
a= nombre del array

a[inicio:fin] #items desde el inicio hasta fin -1

a[inicio:] #items desde el inicio hasta el final del array

a[:fin] #items desde el principio del array hasta fin -1

a[:] #se apunta hacia la memoria donde está almacenado el array

In [31]:
import numpy as np

In [33]:
vector = np.arange(10) #se cera una variable llamada vector, se invoca la libreria numpy, y se da el rango de 10
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
vector[3:]      # ejemplo de a[inicio:] #items desde el inicio hasta el final del array     

array([3, 4, 5, 6, 7, 8, 9])

In [35]:
vector[:8]    #items desde el principio del array hasta fin -1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
vector[:]      #se apunta hacia la memoria donde está almacenado el array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Operaciones con Numpy